# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('grouping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MediaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatserver.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReplyVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('get_time', models.DateTimeField()),
                ('expires_in', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.CharField(help_text='user unique id for this app', max_length=100, primary_key=True, serialize=False)),
                ('subscribe', models.BooleanField(default=False)),
                ('nickname', models.CharField(help_text="user's nickname", max_length=50, null=True)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unknown')], default='F', help_text='user_gender', max_length=1, null=True)),
                ('headimgurl', models.URLField(null=True)),
                ('subscribe_time', models.DateTimeField(null=True)),
                ('remark', models.CharField(blank=True, max_length=30, null=True)),
                ('unionid', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechatserver.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechatserver.Country')),
                ('groupid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wechatserver.Grouping')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechatserver.Language')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wechatserver.Province')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechatserver.Province'),
        ),
    ]
